/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./sky_dome.glb
Author: fangzhangmnm (https://sketchfab.com/fangzhangmnm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sky-dome-demo-a5778d3c90e644e2be1062895ccd44aa
Title: sky dome demo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Dome(props) {
  const { nodes, materials } = useGLTF('/sky_dome.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Skybox_Baked.001']} position={[0, -0.1, 0]} rotation={[0, 1.466, 0]} scale={25} />
    </group>
  )
}

useGLTF.preload('/sky_dome.glb')
