/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 small_villa.glb 
Author: RenderRite (https://sketchfab.com/RenderRite)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-villa-6fc3a756dacd40af8c6e4e3b8e674ea2
Title: Small Villa
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/small_villa.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.111}>
        <mesh geometry={nodes.Material5.geometry} material={materials.Material5} />
        <mesh geometry={nodes.Material58.geometry} material={materials.Material58} />
        <mesh geometry={nodes.Material14.geometry} material={materials.Material14} />
        <mesh geometry={nodes.Material72.geometry} material={materials.Material72} />
        <mesh geometry={nodes.Material67.geometry} material={materials.Material67} />
        <mesh geometry={nodes.Material68.geometry} material={materials.Material68} />
        <mesh geometry={nodes.Material80.geometry} material={materials.Material80} />
        <mesh geometry={nodes.Material83.geometry} material={materials.Material83} />
        <mesh geometry={nodes.Material85.geometry} material={materials.Material85} />
        <mesh geometry={nodes.Material82.geometry} material={materials.Material82} />
        <mesh geometry={nodes.Material19.geometry} material={materials.Material19} />
        <mesh geometry={nodes.Material8.geometry} material={materials.Material8} />
        <mesh geometry={nodes.Material23.geometry} material={materials.Material23} />
        <mesh geometry={nodes.Material23_1.geometry} material={materials.Material23} />
        <mesh geometry={nodes.Material9.geometry} material={materials.Material9} />
        <mesh geometry={nodes.Material33.geometry} material={materials.Material33} />
        <mesh geometry={nodes.Material33_1.geometry} material={materials.Material33} />
        <mesh geometry={nodes.Material33_2.geometry} material={materials.Material33} />
        <mesh geometry={nodes.Material22.geometry} material={materials.Material22} />
        <mesh geometry={nodes.Material22_1.geometry} material={materials.Material22} />
        <mesh geometry={nodes.Material3.geometry} material={materials.Material3} />
        <mesh geometry={nodes.Material7.geometry} material={materials.Material7} />
        <mesh geometry={nodes.Material39.geometry} material={materials.Material39} />
        <mesh geometry={nodes.Material40.geometry} material={materials.Material40} />
        <mesh geometry={nodes.Material43.geometry} material={materials.Material43} />
        <mesh geometry={nodes.Material44.geometry} material={materials.Material44} />
        <mesh geometry={nodes.Material47.geometry} material={materials.Material47} />
        <mesh geometry={nodes.Material48.geometry} material={materials.Material48} />
        <mesh geometry={nodes.Material37.geometry} material={materials.Material37} />
        <mesh geometry={nodes.Material59.geometry} material={materials.Material59} />
        <mesh geometry={nodes.Material57.geometry} material={materials.Material57} />
        <mesh geometry={nodes.Material61.geometry} material={materials.Material61} />
        <mesh geometry={nodes.Material24.geometry} material={materials.Material24} />
        <mesh geometry={nodes.Material62.geometry} material={materials.Material62} />
        <mesh geometry={nodes.Material42.geometry} material={materials.Material42} />
        <mesh geometry={nodes.Material32.geometry} material={materials.Material32} />
        <mesh geometry={nodes.Material32_1.geometry} material={materials.Material32} />
        <mesh geometry={nodes.Material71.geometry} material={materials.Material71} />
        <lineSegments geometry={nodes.Material92.geometry} material={materials.Material92} />
        <mesh geometry={nodes.Material31.geometry} material={materials.Material31} />
        <mesh geometry={nodes.Material76.geometry} material={materials.Material76} />
        <mesh geometry={nodes.Material78.geometry} material={materials.Material78} />
        <mesh geometry={nodes.Material88.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_1.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_2.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_3.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_4.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_5.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_6.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_7.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_8.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material88_9.geometry} material={materials.Material88} />
        <mesh geometry={nodes.Material17.geometry} material={materials.Material17} />
        <mesh geometry={nodes.Material89.geometry} material={materials.Material89} />
        <mesh geometry={nodes.Material90.geometry} material={materials.Material90} />
        <mesh geometry={nodes.Material90_1.geometry} material={materials.Material90} />
        <mesh geometry={nodes.Material91.geometry} material={materials.Material91} />
        <mesh geometry={nodes.Material73.geometry} material={materials.Material73} />
      </group>
    </group>
  )
}

useGLTF.preload('/small_villa.glb')
